name: bluesky_text
description: Provides the easiest and most powerful way to analyze the text for Bluesky Social.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - util

dependencies:
  poptart_xrpc: ^0.1.0
  characters: ^1.4.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.2.0
  import_sorter: ^4.6.0

dependency_overrides:
  poptart_core:
    git:
      url: https://github.com/sprksocial/poptart.git
      ref: f452e900c89930976c185818eb6e350a37ab9808
      path: packages/poptart_core
  poptart_oauth:
    git:
      url: https://github.com/sprksocial/poptart.git
      ref: f452e900c89930976c185818eb6e350a37ab9808
      path: packages/poptart_oauth
  poptart_primitives:
    git:
      url: https://github.com/sprksocial/poptart.git
      ref: f452e900c89930976c185818eb6e350a37ab9808
      path: packages/poptart_primitives
  poptart_xrpc:
    git:
      url: https://github.com/sprksocial/poptart.git
      ref: f452e900c89930976c185818eb6e350a37ab9808
      path: packages/poptart_xrpc
  poptart_multiformats:
    git:
      url: https://github.com/sprksocial/poptart.git
      ref: f452e900c89930976c185818eb6e350a37ab9808
      path: packages/poptart_multiformats
