// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart' as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/objectbox/embedded_post.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6999496775046459021),
    name: 'EmbeddedPost',
    lastPropertyId: const obx_int.IdUid(7, 8430059363224486218),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 2023883478741600837), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3549521277099340373),
        name: 'postUri',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4682420966856057445),
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 115219216497020018), name: 'accountDid', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 2084589381727568380), name: 'source', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 4494373135934411874), name: 'indexedText', type: 9, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7790743710249736574),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 7649439792027952584),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 8430059363224486218), name: 'embeddedAt', type: 12, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6999496775046459021),
    lastIndexId: const obx_int.IdUid(2, 7649439792027952584),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EmbeddedPost: obx_int.EntityDefinition<EmbeddedPost>(
      model: _entities[0],
      toOneRelations: (EmbeddedPost object) => [],
      toManyRelations: (EmbeddedPost object) => {},
      getId: (EmbeddedPost object) => object.id,
      setId: (EmbeddedPost object, int id) {
        object.id = id;
      },
      objectToFB: (EmbeddedPost object, fb.Builder fbb) {
        final postUriOffset = fbb.writeString(object.postUri);
        final accountDidOffset = fbb.writeString(object.accountDid);
        final sourceOffset = fbb.writeString(object.source);
        final indexedTextOffset = fbb.writeString(object.indexedText);
        final embeddingOffset = object.embedding == null ? null : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, postUriOffset);
        fbb.addOffset(2, accountDidOffset);
        fbb.addOffset(3, sourceOffset);
        fbb.addOffset(4, indexedTextOffset);
        fbb.addOffset(5, embeddingOffset);
        fbb.addInt64(6, object.embeddedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final postUriParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 6, '');
        final accountDidParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 8, '');
        final sourceParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 10, '');
        final indexedTextParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 12, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final embeddedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000).round(),
        );
        final object = EmbeddedPost(
          id: idParam,
          postUri: postUriParam,
          accountDid: accountDidParam,
          source: sourceParam,
          indexedText: indexedTextParam,
          embedding: embeddingParam,
          embeddedAt: embeddedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EmbeddedPost] entity fields to define ObjectBox queries.
class EmbeddedPost_ {
  /// See [EmbeddedPost.id].
  static final id = obx.QueryIntegerProperty<EmbeddedPost>(_entities[0].properties[0]);

  /// See [EmbeddedPost.postUri].
  static final postUri = obx.QueryStringProperty<EmbeddedPost>(_entities[0].properties[1]);

  /// See [EmbeddedPost.accountDid].
  static final accountDid = obx.QueryStringProperty<EmbeddedPost>(_entities[0].properties[2]);

  /// See [EmbeddedPost.source].
  static final source = obx.QueryStringProperty<EmbeddedPost>(_entities[0].properties[3]);

  /// See [EmbeddedPost.indexedText].
  static final indexedText = obx.QueryStringProperty<EmbeddedPost>(_entities[0].properties[4]);

  /// See [EmbeddedPost.embedding].
  static final embedding = obx.QueryHnswProperty<EmbeddedPost>(_entities[0].properties[5]);

  /// See [EmbeddedPost.embeddedAt].
  static final embeddedAt = obx.QueryDateNanoProperty<EmbeddedPost>(_entities[0].properties[6]);
}
