import 'package:lazurite/features/auth/data/models/auth_models.dart';

AuthTokens testAuthTokens({
  String accessToken = 'access-token',
  String? refreshToken = 'refresh-token',
  String did = 'did:plc:test',
  String handle = 'test.bsky.social',
  String? displayName,
  String? service = 'bsky.social',
  DateTime? expiresAt,
  String? oauthService,
  String? oauthClientId,
  String? oauthTokenType,
  String? oauthScope,
  String? dpopNonce,
  String? dpopPublicKey,
  String? dpopPrivateKey,
  AuthMethod authMethod = AuthMethod.appPassword,
}) => AuthTokens(
  accessToken: accessToken,
  refreshToken: refreshToken,
  expiresAt: expiresAt ?? DateTime.now().toUtc().add(const Duration(hours: 1)),
  did: did,
  handle: handle,
  displayName: displayName,
  service: service,
  oauthService: oauthService,
  oauthClientId: oauthClientId,
  oauthTokenType: oauthTokenType,
  oauthScope: oauthScope,
  dpopNonce: dpopNonce,
  dpopPublicKey: dpopPublicKey,
  dpopPrivateKey: dpopPrivateKey,
  authMethod: authMethod,
);
