import 'package:lazurite/core/theme/app_theme.dart';
import 'package:lazurite/core/theme/feed_layout.dart';
import 'package:lazurite/features/search/data/search_scope.dart';
import 'package:lazurite/features/settings/bloc/settings_state.dart';

SettingsState testSettingsState({
  AppThemePalette themePalette = AppThemePalette.oxocarbon,
  AppThemeVariant themeVariant = AppThemeVariant.dark,
  bool useSystemTheme = false,
  FeedLayout feedLayout = FeedLayout.comfortable,
  bool animationsEnabled = true,
  bool simulateOffline = false,
  int? threadAutoCollapseDepth,
  String constellationUrl = 'https://constellation.microcosm.blue',
  bool semanticSearchEnabled = true,
  SearchScope searchScope = SearchScope.both,
  int semanticSearchMaxResults = 20,
  String typeaheadProvider = 'bluesky',
  String appViewProvider = 'bluesky',
  bool crossProviderFallbackEnabled = false,
  bool slingshotIdentityFallbackEnabled = false,
  bool crashReportingEnabled = false,
  bool crashReportingConsentPrompted = false,
  int routingEpoch = 0,
  String? appViewHealthSummary,
  DateTime? appViewHealthCheckedAt,
  bool appViewHealthRefreshing = false,
  String? appViewLastFallback,
  String? appViewLastError,
}) => SettingsState(
  themePalette: themePalette,
  themeVariant: themeVariant,
  useSystemTheme: useSystemTheme,
  feedLayout: feedLayout,
  animationsEnabled: animationsEnabled,
  simulateOffline: simulateOffline,
  threadAutoCollapseDepth: threadAutoCollapseDepth,
  constellationUrl: constellationUrl,
  semanticSearchEnabled: semanticSearchEnabled,
  searchScope: searchScope,
  semanticSearchMaxResults: semanticSearchMaxResults,
  typeaheadProvider: typeaheadProvider,
  appViewProvider: appViewProvider,
  crossProviderFallbackEnabled: crossProviderFallbackEnabled,
  slingshotIdentityFallbackEnabled: slingshotIdentityFallbackEnabled,
  crashReportingEnabled: crashReportingEnabled,
  crashReportingConsentPrompted: crashReportingConsentPrompted,
  routingEpoch: routingEpoch,
  appViewHealthSummary: appViewHealthSummary,
  appViewHealthCheckedAt: appViewHealthCheckedAt,
  appViewHealthRefreshing: appViewHealthRefreshing,
  appViewLastFallback: appViewLastFallback,
  appViewLastError: appViewLastError,
);
